port: 7890
allow-lan: true
mode: rule
log-level: info
unified-delay: true
global-client-fingerprint: chrome
dns:
  enable: true
  listen: :53
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver: 
    - 223.5.5.5
    - 8.8.8.8
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - tls://dns.google
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

proxies:
- name: vless-reality-vision-s16               
  type: vless
  server: 213.136.83.240                           
  port: 41761                                
  uuid: 3c0c89ac-5484-4733-b4f5-9de2aada9526   
  network: tcp
  udp: true
  tls: true
  flow: xtls-rprx-vision
  servername: vq4uhlxibksl.serv00.net                 
  reality-opts: 
    public-key: 2MZQRL02RFYTN-JCmFtY13JcNVmmkrICUkcobUtkQmo                      
  client-fingerprint: chrome                  

- name: vmess-ws-s16                         
  type: vmess
  server: 213.136.83.240                       
  port: 62697                                     
  uuid: 3c0c89ac-5484-4733-b4f5-9de2aada9526       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: www.bing.com                    
  ws-opts:
    path: "/3c0c89ac-5484-4733-b4f5-9de2aada9526-vm"                             
    headers:
      Host: www.bing.com                     

- name: hysteria2-s16                            
  type: hysteria2                                      
  server: 213.136.83.240                               
  port: 13644                                
  password: 3c0c89ac-5484-4733-b4f5-9de2aada9526                          
  alpn:
    - h3
  sni: www.bing.com                               
  skip-cert-verify: true
  fast-open: true

- name: vmess-tls-argo-s16                         
  type: vmess
  server: icook.hk                        
  port: 8443                                     
  uuid: 3c0c89ac-5484-4733-b4f5-9de2aada9526       
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  network: ws
  servername: serv00.761513827.xyz                    
  ws-opts:
    path: "/3c0c89ac-5484-4733-b4f5-9de2aada9526-vm"                             
    headers:
      Host: serv00.761513827.xyz

- name: vmess-argo-s16                         
  type: vmess
  server: icook.hk                        
  port: 8880                                     
  uuid: 3c0c89ac-5484-4733-b4f5-9de2aada9526       
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  network: ws
  servername: serv00.761513827.xyz                   
  ws-opts:
    path: "/3c0c89ac-5484-4733-b4f5-9de2aada9526-vm"                             
    headers:
      Host: serv00.761513827.xyz 

proxy-groups:
- name: Balance
  type: load-balance
  url: https://www.gstatic.com/generate_204
  interval: 300
  strategy: round-robin
  proxies:
    - vless-reality-vision-s16                              
    - vmess-ws-s16
    - hysteria2-s16
    - vmess-tls-argo-s16
    - vmess-argo-s16

- name: Auto
  type: url-test
  url: https://www.gstatic.com/generate_204
  interval: 300
  tolerance: 50
  proxies:
    - vless-reality-vision-s16                             
    - vmess-ws-s16
    - hysteria2-s16
    - vmess-tls-argo-s16
    - vmess-argo-s16
    
- name: Select
  type: select
  proxies:
    - Balance                                         
    - Auto
    - DIRECT
    - vless-reality-vision-s16                              
    - vmess-ws-s16
    - hysteria2-s16
    - vmess-tls-argo-s16
    - vmess-argo-s16
rules:
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Select
  
